apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: stage
spec:
  selector:
    matchLabels:
      app: s-catalog
  template:
    metadata:
      labels:
        app: s-catalog
    spec:
      containers:
      - name: s-catalog-cntr
        image: localhost:5000/catalog-srv
        ports:
        - name: http
          containerPort: 9003
        env:
          - name: GREET_URL
            value: s-greet
          - name: TIME_URL
            # also: s-time.stage.svc.cluster.local
            value: s-time.stage.svc.cluster.local
          - name: NODE_IP
            value: "192.168.64.3"
          - name: WORKY_PORT
            value: "30012"
