apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s-catalog
  namespace: stage
spec:
  rules:
  - host: catalog.showdown
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: s-catalog
            port:
              name: main
