apiVersion: skaffold/v2beta10
kind: Config

build:
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: true
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - image: localhost:5000/time-srv
    context: services/time
    sync:
      infer:
      - 'services/time/*'
  - image: localhost:5000/greet-srv
    context: services/greet
    sync:
      infer:
      - 'services/greet/*'
  - image: localhost:5000/catalog-srv
    context: services/catalog
    sync:
      infer:
      - 'services/catalog/*'
  - image: localhost:5000/worky-srv
    context: services/worky
    sync:
      infer:
      - 'services/worky/*'

# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - ./services/time/k8s/*
    - ./services/greet/k8s/*
    - ./services/catalog/k8s/*
    - ./services/worky/k8s/*
