apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: s-time
  namespace: stage
spec:
  rules:
  - host: time.showdown
    http:
      paths:
      - backend:
          serviceName: s-time
          servicePort: main
        path: /
