apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        volumeMounts:
        - name: prometheus-cm
          mountPath: /etc/prometheus
        ports:
        - containerPort: 80
      securityContext:
        runAsUser: 0
      volumes:
        - name: prometheus-cm
          configMap:
            name: prometheus-cm
